name: CDC Infrastructure
run-name: CDC Infrastructure
on: 
    workflow_dispatch

jobs:
    foo:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Log level: $LEVEL"
                echo "Tags: $TAGS"
                echo "Environment: $ENVIRONMENT"
              env:
                LEVEL: ${{ inputs.logLevel }}
                TAGS: ${{ inputs.tags }}
                ENVIRONMENT: ${{ inputs.environment }}